# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-sync" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "e388773368b3e54409086a68361f9f3d2dc04cbcd57265c86f3f065aa6e4a1ea"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f0098f61e503b7e09b18975b530ee59e516bfdecb2d5e87cf3cf85a1a2b2de6"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99b287a806fd77fd7dd67f48225ee48c69e109eaccf082635c3300cd8dee4ea7"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80ad8c2c4acbd9686b7e0ac7acaedd24cc9ab40c6b8b481c4afcba50fa233b58"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_arm64.tar.gz"
    end
  end

  name "env-sync"
  desc "Sync environment variables to Vercel or GitHub Actions from a definition file"
  homepage "https://github.com/ptyhard/env-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-sync"

  # No zap stanza required

end
