# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-sync" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "14ba38de4060082119062969756eb9f53a116ffb14f7a328f38957b514f861ab"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85a4db2ead6c39e0f2d7dee93ec50164c1e5bfd7434e6345a17226c7ffbbcc56"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b229ada2c5af517155c2a53e7c6599028803a7220b70cd438e0d7397fd75b91f"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "97607dbc41a05d97d566f03210ecf1874e7e92e32d40b14c5d75ced4a2f99443"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_arm64.tar.gz"
    end
  end

  name "env-sync"
  desc "Sync environment variables to Vercel or GitHub Actions from a definition file"
  homepage "https://github.com/ptyhard/env-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-sync"

  # No zap stanza required

end
