# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-sync" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "9cb3d69dace01c8679bb3c63e66c7cec65ac774b3d7053a65fd8dbf7e990c56e"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "003481730810a416e25870a1e23ac8b34c07177e2d2e2811eee6a63b319fe48a"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1aa46aec8e65b63df43970852aff8f610bbb28e304a3d60cc59df5cb097aa43c"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56c12bd5be9b37606a6aa2b4a2bde681d6ac48db591d22b2278e3c2ee5f6640b"
      url "https://github.com/ptyhard/env-sync/releases/download/v#{version}/env-sync_linux_arm64.tar.gz"
    end
  end

  name "env-sync"
  desc "Sync environment variables to Vercel or GitHub Actions from a definition file"
  homepage "https://github.com/ptyhard/env-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-sync"

  # No zap stanza required

end
