# This file was generated by GoReleaser. DO NOT EDIT.
cask "vercel-env-sync" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "59f52db114d96f6d1fbb4fa328f5f70be3c713aefe13739cd4c6e4fd9a414a67"
      url "https://github.com/ptyhard/vercel-env-sync/releases/download/v#{version}/vercel-env-sync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c05b24e37518bb1e66eba23ef8dd9c3f94617106b7df7b051bd857a05f119b24"
      url "https://github.com/ptyhard/vercel-env-sync/releases/download/v#{version}/vercel-env-sync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9890bdade38ec9157eba559e983f5753317670160963b72a9b7c3178f6e1cb33"
      url "https://github.com/ptyhard/vercel-env-sync/releases/download/v#{version}/vercel-env-sync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f2e773d56793ad7e833fb870b556bf31bb84e1b002bcae33d66e0f55694e7b7"
      url "https://github.com/ptyhard/vercel-env-sync/releases/download/v#{version}/vercel-env-sync_linux_arm64.tar.gz"
    end
  end

  name "vercel-env-sync"
  desc "Sync environment variables to Vercel from a definition file"
  homepage "https://github.com/ptyhard/vercel-env-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vercel-env-sync"

  # No zap stanza required

end
